#!/usr/bin/env sh

mkdir /work/packages

# cp /work/hostdir/binpkgs/aquamarine*.xbps /work/packages
# cp /work/hostdir/binpkgs/hypr*.xbps /work/packages
# cp /work/hostdir/binpkgs/xdg-desktop-portal-hyprland*.xbps /work/packages
# cp /work/hostdir/binpkgs/sdbus-cpp*.xbps /work/packages
# cp /work/hostdir/binpkgs/tomlplusplus*.xbps /work/packages
cp /work/hostdir/binpkgs/zen-browser*.xbps /work/packages
cd /work/packages
xbps-rindex -a *

