#!/usr/bin/env sh

# Retrieve the signing key from the separate private repository

COMMAND="
  curl \
    -H 'Authorization: token $(cat /work/PEM_PAT_TOKEN)' \
    -H 'Accept: application/vnd.github.v3.raw' \
    -O -L https://api.github.com/repos/$REPO_OWNER/hyprland-void-private-pem/contents/private.pem
"

echo "Running command: $COMMAND"
echo "$PEM_PAT_TOKEN" >> /work/PEM_PAT_TOKEN # Hide secret from being printed to the log
sh -c "$COMMAND"

