#!/usr/bin/env sh

# We need to sign the packages with our private key so that they will be accepted by xbps remotely
# See: https://docs.voidlinux.org/xbps/repositories/signing.html

COMMAND="
  # Retrieve the signing key from the separate private repository
  cd /work
  curl \
    -H 'Authorization: token $PEM_PAT' \
    -H 'Accept: application/vnd.github.v3.raw' \
    -O -L https://api.github.com/repos/$REPO_OWNER/hyprland-void-private-pem/contents/private.pem

  # Sign packages
  xbps-rindex --privkey /work/private.pem --sign --signedby \"$REPO_NAME-github-action\" /work/packages
  xbps-rindex --privkey /work/private.pem --sign-pkg /work/packages/*.xbps
"

echo "Running command: $COMMAND"
sh -c "$COMMAND"

